# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn insidelab.wsgi:application --bind 0.0.0.0:$PORT"
