# Generated by Django 4.2.7 on 2025-09-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_professor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('research_areas', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_groups', to='universities.professor')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_groups', to='universities.university')),
            ],
            options={
                'db_table': 'research_groups',
                'ordering': ['university__name', 'department', 'name'],
                'unique_together': {('university', 'department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Optional research group within the department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='universities.researchgroup'),
        ),
    ]
