# Generated by Django 4.2.7 on 2025-09-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_researchgroup_professor_research_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('common_names', models.JSONField(default=list, help_text="Alternative names for this department (e.g., 'CS', 'CompSci')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='researchgroup',
            options={'ordering': ['university_department__university__name', 'university_department__department__name', 'name']},
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, help_text='Legacy field - use university_department instead', max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use university_department instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_professors', to='universities.university'),
        ),
        migrations.CreateModel(
            name='UniversityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(blank=True, help_text='University-specific name if different from standard name', max_length=200)),
                ('website', models.URLField(blank=True)),
                ('head_name', models.CharField(blank=True, max_length=200)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_departments', to='universities.department')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_departments', to='universities.university')),
            ],
            options={
                'db_table': 'university_departments',
                'ordering': ['university__name', 'department__name'],
                'unique_together': {('university', 'department')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='researchgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='professor',
            name='university_department',
            field=models.ForeignKey(blank=True, help_text='The specific university-department combination', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='universities.universitydepartment'),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='university_department',
            field=models.ForeignKey(blank=True, help_text='The specific university-department combination this group belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_groups', to='universities.universitydepartment'),
        ),
        migrations.AlterUniqueTogether(
            name='researchgroup',
            unique_together={('university_department', 'name')},
        ),
        migrations.RemoveField(
            model_name='researchgroup',
            name='department',
        ),
        migrations.RemoveField(
            model_name='researchgroup',
            name='university',
        ),
    ]
