# Generated by Django 4.2.7 on 2025-09-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_add_department_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Email domain (e.g., kaist.ac.kr, snu.ac.kr)', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this domain has been verified as legitimate')),
                ('verification_type', models.CharField(choices=[('official', 'Official University Domain'), ('student', 'Student Email Domain'), ('faculty', 'Faculty Email Domain'), ('staff', 'Staff Email Domain'), ('alumni', 'Alumni Email Domain')], default='official', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this domain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='universities.university')),
            ],
            options={
                'db_table': 'university_email_domains',
                'ordering': ['university__name', 'domain'],
                'indexes': [models.Index(fields=['domain'], name='university__domain_78e6b7_idx'), models.Index(fields=['university', 'is_active'], name='university__univers_1c9db1_idx')],
            },
        ),
    ]
