# Generated by Django 4.2.7 on 2025-10-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_remove_lab_professors'),
        ('universities', '0005_universityemaildomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='lab',
            field=models.ForeignKey(blank=True, help_text='Lab this professor belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='labs.lab'),
        ),
    ]
