# Generated by Django 4.2.7 on 2025-10-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_add_professor_rating_fields'),
        ('universities', '0006_professor_lab'),
    ]

    operations = [
    ]
