# Generated by Django 4.2.7 on 2026-01-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_merge_20251030_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='scholar_id',
            field=models.CharField(blank=True, help_text='Google Scholar author ID for scraping publications', max_length=100),
        ),
    ]
