# Generated by Django 4.2.7 on 2025-10-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
