# Generated by Django 4.2.7 on 2025-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='tier',
            field=models.CharField(choices=[('top', 'Top Tier'), ('high', 'High Tier'), ('mid', 'Mid Tier'), ('workshop', 'Workshop')], default='mid', max_length=10),
        ),
    ]
