# Generated by Django 4.2.7 on 2025-10-09 05:42

from django.db import migrations
from django.db import models


def populate_venue_tiers(apps, schema_editor):
    """Populate venue tiers based on your classification"""
    Venue = apps.get_model('publications', 'Venue')

    # Top-tier (S급) venues
    top_tier_venues = [
        # Machine Learning & AI
        'NeurIPS', 'Neural Information Processing Systems',
        'ICML', 'International Conference on Machine Learning',
        'ICLR', 'International Conference on Learning Representations',
        'AAAI', 'Association for the Advancement of Artificial Intelligence',
        'IJCAI', 'International Joint Conference on Artificial Intelligence',

        # Computer Vision
        'CVPR', 'Computer Vision and Pattern Recognition',
        'ICCV', 'International Conference on Computer Vision',
        'ECCV', 'European Conference on Computer Vision',

        # Natural Language Processing
        'ACL', 'Association for Computational Linguistics',
        'Annual Meeting of the Association for Computational Linguistics',
        'EMNLP', 'Empirical Methods in Natural Language Processing',
        'NAACL', 'North American Chapter of ACL',

        # Systems & Architecture
        'OSDI', 'Operating Systems Design and Implementation',
        'SOSP', 'Symposium on Operating Systems Principles',
        'ISCA', 'International Symposium on Computer Architecture',
        'MICRO', 'IEEE/ACM International Symposium on Microarchitecture',

        # Networking & Security
        'SIGCOMM', 'ACM Special Interest Group on Data Communication',
        'NSDI', 'Networked Systems Design and Implementation',
        'NDSS', 'Network and Distributed System Security',
        'CCS', 'ACM Conference on Computer and Communications Security',
        'USENIX Security', 'USENIX Security Symposium',
        'IEEE S&P', 'IEEE Symposium on Security and Privacy',

        # Software Engineering
        'ICSE', 'International Conference on Software Engineering',
        'FSE', 'Foundations of Software Engineering',
        'PLDI', 'Programming Language Design and Implementation',

        # Database & Data Mining
        'SIGMOD', 'ACM Special Interest Group on Management of Data',
        'VLDB', 'Very Large Data Bases',
        'KDD', 'Knowledge Discovery and Data Mining',
        'ICDE', 'International Conference on Data Engineering',

        # Human-Computer Interaction
        'CHI', 'Conference on Human Factors in Computing Systems',
        'UIST', 'User Interface Software and Technology',

        # Theory
        'STOC', 'Symposium on Theory of Computing',
        'FOCS', 'Foundations of Computer Science',

        # Electrical Engineering
        'ISSCC', 'International Solid-State Circuits Conference',
        'DAC', 'Design Automation Conference',
        'ICCAD', 'International Conference on Computer-Aided Design',
        'ICASSP', 'International Conference on Acoustics, Speech and Signal Processing',
        'APEC', 'Applied Power Electronics Conference',
        'ECCE', 'Energy Conversion Congress and Exposition',
        'ICC', 'International Conference on Communications',
        'GLOBECOM', 'Global Communications Conference',
    ]

    # High-tier (A급) venues
    high_tier_venues = [
        # Machine Learning & AI
        'AISTATS', 'Artificial Intelligence and Statistics',
        'UAI', 'Uncertainty in Artificial Intelligence',
        'CoRL', 'Conference on Robot Learning',
        'COLT', 'Conference on Learning Theory',

        # Computer Vision
        'BMVC', 'British Machine Vision Conference',
        'WACV', 'Winter Conference on Applications of Computer Vision',
        '3DV', 'International Conference on 3D Vision',

        # Natural Language Processing
        'CoNLL', 'Conference on Computational Natural Language Learning',
        'EACL', 'European Chapter of ACL',
        'COLING', 'International Conference on Computational Linguistics',

        # Robotics
        'ICRA', 'International Conference on Robotics and Automation',
        'IROS', 'International Conference on Intelligent Robots and Systems',
        'RSS', 'Robotics: Science and Systems',

        # Systems & Architecture
        'ASPLOS', 'Architectural Support for Programming Languages and Operating Systems',
        'EuroSys', 'European Conference on Computer Systems',
        'HPCA', 'High Performance Computer Architecture',
        'ATC', 'USENIX Annual Technical Conference',

        # Networking & Security
        'INFOCOM', 'IEEE International Conference on Computer Communications',
        'IMC', 'Internet Measurement Conference',
        'CRYPTO', 'International Cryptology Conference',
        'EUROCRYPT', 'European Cryptology Conference',

        # Software Engineering
        'ASE', 'Automated Software Engineering',
        'ISSTA', 'International Symposium on Software Testing and Analysis',
        'OOPSLA', 'Object-Oriented Programming, Systems, Languages & Applications',

        # Database & Data Mining
        'ICDM', 'International Conference on Data Mining',
        'SDM', 'SIAM International Conference on Data Mining',
        'WSDM', 'Web Search and Data Mining',

        # Graphics & Multimedia
        'SIGGRAPH', 'Special Interest Group on Computer Graphics',
        'SIGGRAPH Asia',
        'ACM MM', 'ACM Multimedia',

        # HCI
        'CSCW', 'Computer-Supported Cooperative Work',
        'IUI', 'Intelligent User Interfaces',

        # Electrical Engineering
        'ISCAS', 'International Symposium on Circuits and Systems',
        'VLSI', 'Symposium on VLSI Circuits',
        'EMSOFT', 'International Conference on Embedded Software',
        'RTAS', 'Real-Time and Embedded Technology and Applications Symposium',
        'DATE', 'Design, Automation & Test in Europe',
        'EUSIPCO', 'European Signal Processing Conference',
        'WCNC', 'Wireless Communications and Networking Conference',
        'VTC', 'Vehicular Technology Conference',

        # Industrial & Systems Engineering
        'WSC', 'Winter Simulation Conference',
        'CASE', 'Conference on Automation Science and Engineering',
        'ETFA', 'Emerging Technologies and Factory Automation',
        'HFES', 'Human Factors and Ergonomics Society Annual Meeting',
    ]

    # Mid-tier (B급) venues
    mid_tier_venues = [
        # Machine Learning & AI
        'ECAI', 'European Conference on Artificial Intelligence',
        'PRICAI', 'Pacific Rim International Conference on AI',
        'ICANN', 'International Conference on Artificial Neural Networks',

        # Computer Vision
        'ACCV', 'Asian Conference on Computer Vision',
        'ICIP', 'International Conference on Image Processing',
        'ICPR', 'International Conference on Pattern Recognition',

        # Robotics
        'Humanoids', 'IEEE-RAS International Conference on Humanoid Robots',
        'ICARCV', 'International Conference on Control, Automation, Robotics and Vision',

        # Systems
        'MIDDLEWARE', 'ACM/IFIP/USENIX Middleware Conference',
        'ICDCS', 'International Conference on Distributed Computing Systems',
        'CLUSTER', 'IEEE International Conference on Cluster Computing',

        # Networking
        'ICNP', 'International Conference on Network Protocols',
        'CONEXT', 'Conference on Emerging Networking Experiments and Technologies',

        # Software Engineering
        'ICSME', 'International Conference on Software Maintenance and Evolution',
        'ICPC', 'International Conference on Program Comprehension',
        'MSR', 'Mining Software Repositories',

        # Web & IR
        'WWW', 'The Web Conference',
        'SIGIR', 'Special Interest Group on Information Retrieval',
        'CIKM', 'Conference on Information and Knowledge Management',

        # Electrical Engineering
        'MWSCAS', 'Midwest Symposium on Circuits and Systems',
        'ACC', 'American Control Conference',
        'CDC', 'Conference on Decision and Control',

        # Industrial Engineering
        'IIE Annual Conference',
        'IISE', 'Institute of Industrial and Systems Engineers Conference',
        'FAIM', 'Flexible Automation and Intelligent Manufacturing',
        'CIRP', 'International Academy for Production Engineering',
    ]

    # Update venue tiers
    for venue_name in top_tier_venues:
        Venue.objects.filter(
            models.Q(name__icontains=venue_name) |
            models.Q(short_name__icontains=venue_name)
        ).update(tier='top')

    for venue_name in high_tier_venues:
        Venue.objects.filter(
            models.Q(name__icontains=venue_name) |
            models.Q(short_name__icontains=venue_name)
        ).update(tier='high')

    for venue_name in mid_tier_venues:
        Venue.objects.filter(
            models.Q(name__icontains=venue_name) |
            models.Q(short_name__icontains=venue_name)
        ).update(tier='mid')

    # Set workshop type venues to workshop tier
    Venue.objects.filter(type='workshop').update(tier='workshop')

    # Update Advances in Neural Information Processing Systems to top tier (it's NeurIPS)
    Venue.objects.filter(name__icontains='Advances in Neural Information Processing Systems').update(tier='top')


def reverse_populate_venue_tiers(apps, schema_editor):
    """Reverse migration - reset all tiers to mid"""
    Venue = apps.get_model('publications', 'Venue')
    Venue.objects.all().update(tier='mid')


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_update_venue_tier_choices'),
    ]

    operations = [
        migrations.RunPython(populate_venue_tiers, reverse_populate_venue_tiers),
    ]