# Generated by Django 4.2.7 on 2025-11-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_populate_research_areas_by_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcharea',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
