# Generated by Django 4.2.7 on 2025-12-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_researcharea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='논문 키워드 목록 (JSON 배열)'),
        ),
    ]
