# Generated by Django 4.2.7 on 2025-12-28 09:29

from django.db import migrations
import json


def fix_keywords_format(apps, schema_editor):
    """Convert Python list objects to JSON strings in keywords field"""
    # Skip this migration - SafeJSONField handles the conversion automatically
    # This migration was causing issues with existing ArrayField data
    pass


def reverse_keywords_format(apps, schema_editor):
    """Reverse operation - convert back to string format if needed"""
    Publication = apps.get_model('publications', 'Publication')

    for publication in Publication.objects.all():
        if publication.keywords and isinstance(publication.keywords, list):
            # Keep as list (JSONField handles serialization)
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_alter_publication_keywords'),
    ]

    operations = [
        migrations.RunPython(
            fix_keywords_format,
            reverse_keywords_format,
        ),
    ]
