# Generated by Django 4.2.7 on 2025-12-28 09:29

from django.db import migrations
import json


def fix_keywords_format(apps, schema_editor):
    """Convert Python list objects to JSON strings in keywords field"""
    db_alias = schema_editor.connection.alias

    # Use raw SQL to handle the data conversion safely
    with schema_editor.connection.cursor() as cursor:
        # First, check if the table exists
        try:
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.tables
                WHERE table_name = 'publications'
            """)
            if cursor.fetchone()[0] == 0:
                return  # Table doesn't exist, skip migration
        except:
            # If information_schema doesn't exist (SQLite), try direct access
            try:
                cursor.execute("SELECT COUNT(*) FROM publications LIMIT 1")
            except:
                return  # Table doesn't exist, skip migration

        # Update keywords field to handle existing data
        try:
            # For PostgreSQL: Convert any non-JSON values to empty array
            cursor.execute("""
                UPDATE publications
                SET keywords = '[]'::json
                WHERE keywords IS NULL
                   OR keywords = ''
                   OR (keywords::text !~ '^[\\[\\{]')
            """)
        except:
            # For SQLite or other databases: simpler approach
            try:
                cursor.execute("""
                    UPDATE publications
                    SET keywords = '[]'
                    WHERE keywords IS NULL
                       OR keywords = ''
                       OR keywords NOT LIKE '[%'
                       AND keywords NOT LIKE '{%'
                """)
            except:
                # If all else fails, just set empty arrays
                cursor.execute("UPDATE publications SET keywords = '[]'")

        schema_editor.connection.commit()


def reverse_keywords_format(apps, schema_editor):
    """Reverse operation - convert back to string format if needed"""
    Publication = apps.get_model('publications', 'Publication')

    for publication in Publication.objects.all():
        if publication.keywords and isinstance(publication.keywords, list):
            # Keep as list (JSONField handles serialization)
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_alter_publication_keywords'),
    ]

    operations = [
        migrations.RunPython(
            fix_keywords_format,
            reverse_keywords_format,
        ),
    ]
