# Generated by Django 4.2.7 on 2025-12-28 09:29

from django.db import migrations
import json


def fix_keywords_format(apps, schema_editor):
    """Convert Python list objects to JSON strings in keywords field"""
    Publication = apps.get_model('publications', 'Publication')

    for publication in Publication.objects.all():
        if publication.keywords is not None:
            # If keywords is already a list (from ArrayField), convert to JSON
            if isinstance(publication.keywords, list):
                # Already in correct format for JSONField
                continue
            elif isinstance(publication.keywords, str):
                try:
                    # Try to parse as JSON
                    parsed = json.loads(publication.keywords)
                    if isinstance(parsed, list):
                        publication.keywords = parsed
                        publication.save(update_fields=['keywords'])
                except json.JSONDecodeError:
                    # If not valid JSON, convert string to list
                    publication.keywords = [publication.keywords] if publication.keywords else []
                    publication.save(update_fields=['keywords'])
            else:
                # Convert other types to empty list
                publication.keywords = []
                publication.save(update_fields=['keywords'])


def reverse_keywords_format(apps, schema_editor):
    """Reverse operation - convert back to string format if needed"""
    Publication = apps.get_model('publications', 'Publication')

    for publication in Publication.objects.all():
        if publication.keywords and isinstance(publication.keywords, list):
            # Keep as list (JSONField handles serialization)
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_alter_publication_keywords'),
    ]

    operations = [
        migrations.RunPython(
            fix_keywords_format,
            reverse_keywords_format,
        ),
    ]
