# Generated by Django 4.2.7 on 2025-12-28 13:55

import apps.publications.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_fix_keywords_json_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=apps.publications.models.SafeJSONField(blank=True, default=list, help_text='논문 키워드 목록 (JSON 배열)'),
        ),
    ]
