# Generated by Django 4.2.7 on 2026-01-21 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_professor_scholar_id'),
        ('publications', '0011_use_safe_jsonfield_for_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='스크래핑 상태', max_length=20)),
                ('publications_count', models.PositiveIntegerField(default=0, help_text='수집된 논문 수')),
                ('execution_time_seconds', models.PositiveIntegerField(default=0, help_text='실행 시간 (초)')),
                ('error_message', models.TextField(blank=True, help_text='에러 메시지 (실패 시)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(help_text='스크래핑 대상 교수', on_delete=django.db.models.deletion.CASCADE, related_name='scraping_logs', to='universities.professor')),
            ],
            options={
                'db_table': 'scraping_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['professor', '-created_at'], name='scraping_lo_profess_b9a9ac_idx'), models.Index(fields=['status'], name='scraping_lo_status_117ee5_idx')],
            },
        ),
    ]
