# Generated by Django 4.2.7 on 2025-09-01 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('lab_size', models.IntegerField(blank=True, null=True)),
                ('research_areas', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='universities.professor')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='universities.university')),
            ],
            options={
                'db_table': 'labs',
                'ordering': ['-overall_rating', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('funding_info', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_topics', to='labs.lab')),
            ],
            options={
                'db_table': 'research_topics',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recruiting_phd', models.BooleanField(default=False)),
                ('is_recruiting_postdoc', models.BooleanField(default=False)),
                ('is_recruiting_intern', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_status', to='labs.lab')),
            ],
            options={
                'verbose_name_plural': 'Recruitment statuses',
                'db_table': 'recruitment_status',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('venue', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('citations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_publications', to='labs.lab')),
            ],
            options={
                'db_table': 'publications',
                'ordering': ['-year', '-citations'],
            },
        ),
    ]
