# Generated by Django 4.2.7 on 2025-09-16 05:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_status'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategoryAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.ratingcategory')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_averages', to='labs.lab')),
            ],
            options={
                'db_table': 'lab_category_averages',
                'ordering': ['lab', 'category__sort_order'],
                'indexes': [models.Index(fields=['lab', 'category'], name='lab_categor_lab_id_3142a6_idx'), models.Index(fields=['category', 'average_rating'], name='lab_categor_categor_a7572a_idx'), models.Index(fields=['lab', 'average_rating'], name='lab_categor_lab_id_fe849a_idx')],
                'unique_together': {('lab', 'category')},
            },
        ),
    ]
