# Generated by Django 4.2.7 on 2025-09-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_researchgroup_professor_research_group'),
        ('labs', '0002_labcategoryaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='research_group',
            field=models.ForeignKey(blank=True, help_text='Optional research group this lab belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='universities.researchgroup'),
        ),
    ]
