# Generated by Django 4.2.7 on 2025-09-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_add_department_models'),
        ('labs', '0003_lab_research_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='university_department',
            field=models.ForeignKey(blank=True, help_text='The specific university-department combination', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='universities.universitydepartment'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='department',
            field=models.CharField(blank=True, help_text='Legacy field - use university_department instead', max_length=200),
        ),
        migrations.AlterField(
            model_name='lab',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use university_department instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_labs', to='universities.university'),
        ),
    ]
