# Generated by Django 4.2.7 on 2025-09-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_add_university_department_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publication',
            table='lab_publications',
        ),
    ]
