# Generated by Django 4.2.7 on 2025-10-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_universityemaildomain'),
        ('labs', '0005_alter_publication_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='head_professor',
            field=models.ForeignKey(blank=True, help_text='Primary professor who heads this lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_labs', to='universities.professor'),
        ),
        migrations.AddField(
            model_name='lab',
            name='professors',
            field=models.ManyToManyField(blank=True, help_text='All professors associated with this lab', related_name='labs', to='universities.professor'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='professor',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use head_professor and professors instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_labs', to='universities.professor'),
        ),
    ]
