# Generated by Django 4.2.7 on 2025-10-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_lab_head_professor_lab_professors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='professors',
        ),
    ]
