# Generated by Django 4.2.7 on 2025-10-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_remove_lab_professors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='professor',
        ),
    ]
