# Generated by Django 4.2.7 on 2025-10-30 12:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0008_remove_lab_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('mock_interview', 'Mock Interview'), ('qa_session', 'Q&A Session')], default='mock_interview', max_length=20)),
                ('focus_areas', models.TextField(blank=True, help_text='Areas of focus or topics to cover')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional notes or requests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matching', 'Matching'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('match_type', models.CharField(blank=True, choices=[('exact-lab', 'Exact Lab Match'), ('same-department', 'Same Department Match'), ('same-field', 'Same Field Match')], help_text='Type of match when interviewer is assigned', max_length=20, null=True)),
                ('confirmed_date', models.DateField(blank=True, help_text='Confirmed session date', null=True)),
                ('confirmed_time', models.TimeField(blank=True, help_text='Confirmed session time', null=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price in USD', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(blank=True, help_text='Assigned interviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who booked this session', on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mock_interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Preferred date')),
                ('time', models.TimeField(help_text='Preferred time')),
                ('priority', models.IntegerField(default=1, help_text='Priority order (1 = first choice, 2 = second, 3 = third)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slots', to='booking_sessions.mockinterviewsession')),
            ],
            options={
                'db_table': 'session_time_slots',
                'ordering': ['priority'],
                'indexes': [models.Index(fields=['session', 'priority'], name='session_tim_session_159bee_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, help_text='Priority order (1 = highest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(help_text='Target lab for matching', on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_labs', to='booking_sessions.mockinterviewsession')),
            ],
            options={
                'db_table': 'session_labs',
                'ordering': ['priority'],
                'unique_together': {('session', 'lab')},
            },
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['user', 'status'], name='mock_interv_user_id_f972dd_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['interviewer', 'status'], name='mock_interv_intervi_81465d_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['status', 'created_at'], name='mock_interv_status_47924c_idx'),
        ),
    ]
