# Generated by Django 4.2.7 on 2025-12-28 14:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0011_use_safe_jsonfield_for_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0008_remove_lab_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('mock_interview', 'Mock Interview'), ('qa_session', 'Q&A Session')], default='mock_interview', max_length=20)),
                ('focus_areas', models.TextField(blank=True, help_text='Specific focus areas or topics to cover in the interview')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional notes or requests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matching', 'Matching'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('match_type', models.CharField(blank=True, choices=[('exact-lab', 'Exact Lab Match'), ('same-department', 'Same Department Match'), ('same-field', 'Same Field Match')], help_text='Type of match when interviewer is assigned', max_length=20, null=True)),
                ('confirmed_date', models.DateField(blank=True, help_text='Confirmed session date', null=True)),
                ('confirmed_time', models.TimeField(blank=True, help_text='Confirmed session time', null=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price in USD', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('zoom_link', models.URLField(blank=True, help_text='Zoom meeting link for confirmed sessions')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when session was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(blank=True, help_text='Assigned interviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('research_area', models.ForeignKey(blank=True, help_text='Legacy field - use research_areas relationship instead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.researcharea')),
                ('user', models.ForeignKey(help_text='User who booked this session', on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('interviewee', 'Interviewee'), ('interviewer', 'Interviewer')], help_text='Type of reviewer (interviewee or interviewer)', max_length=20)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True, help_text='Optional review comment')),
                ('communication_rating', models.IntegerField(blank=True, help_text='Communication skills rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('preparation_rating', models.IntegerField(blank=True, help_text='Preparation level rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('helpfulness_rating', models.IntegerField(blank=True, help_text='Helpfulness rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this review is active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(help_text='User who gave this review', on_delete=django.db.models.deletion.CASCADE, related_name='interview_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Interview session being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='interviews.mockinterviewsession')),
            ],
            options={
                'db_table': 'interview_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Preferred date')),
                ('time', models.TimeField(help_text='Preferred time')),
                ('priority', models.IntegerField(default=1, help_text='Priority order (1 = first choice, 2 = second, 3 = third)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_slots', to='interviews.mockinterviewsession')),
            ],
            options={
                'db_table': 'session_time_slots',
                'ordering': ['priority'],
                'indexes': [models.Index(fields=['session', 'priority'], name='session_tim_session_159bee_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, help_text='Priority order (1 = highest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_area', models.ForeignKey(help_text='Research area for matching', on_delete=django.db.models.deletion.CASCADE, to='publications.researcharea')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_areas', to='interviews.mockinterviewsession')),
            ],
            options={
                'db_table': 'session_research_areas',
                'ordering': ['priority'],
                'unique_together': {('session', 'research_area')},
            },
        ),
        migrations.CreateModel(
            name='SessionLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, help_text='Priority order (1 = highest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(help_text='Target lab for matching', on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_labs', to='interviews.mockinterviewsession')),
            ],
            options={
                'db_table': 'session_labs',
                'ordering': ['priority'],
                'unique_together': {('session', 'lab')},
            },
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['user', 'status'], name='interview_s_user_id_88a9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['interviewer', 'status'], name='interview_s_intervi_634c38_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['status', 'created_at'], name='interview_s_status_ba875c_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewreview',
            index=models.Index(fields=['session', 'reviewer_type'], name='interview_r_session_68cb79_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewreview',
            index=models.Index(fields=['reviewer', 'reviewer_type'], name='interview_r_reviewe_45335e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewreview',
            index=models.Index(fields=['rating', 'is_active'], name='interview_r_rating_995ce6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewreview',
            unique_together={('session', 'reviewer', 'reviewer_type')},
        ),
    ]
