# Generated by Django 4.2.7 on 2025-10-30 12:45
# Fake migration - tables already exist from previous sessions app

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0008_remove_lab_professor'),
        ('authentication', '0002_add_user_research_profile'),
    ]

    operations = [
        # Empty operations - tables already exist
        # This is a fake migration to handle the rename from sessions to interviews
    ]
