# Generated by Django 4.2.7 on 2025-11-21 06:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_populate_research_areas_by_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0006_add_zoom_and_completed_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinterviewsession',
            name='research_area',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use research_areas relationship instead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.researcharea'),
        ),
        migrations.CreateModel(
            name='InterviewReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('interviewee', 'Interviewee'), ('interviewer', 'Interviewer')], help_text='Type of reviewer (interviewee or interviewer)', max_length=20)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True, help_text='Optional review comment')),
                ('communication_rating', models.IntegerField(blank=True, help_text='Communication skills rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('preparation_rating', models.IntegerField(blank=True, help_text='Preparation level rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('helpfulness_rating', models.IntegerField(blank=True, help_text='Helpfulness rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this review is active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(help_text='User who gave this review', on_delete=django.db.models.deletion.CASCADE, related_name='interview_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Interview session being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='interviews.mockinterviewsession')),
            ],
            options={
                'db_table': 'interview_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'reviewer_type'], name='interview_r_session_68cb79_idx'), models.Index(fields=['reviewer', 'reviewer_type'], name='interview_r_reviewe_45335e_idx'), models.Index(fields=['rating', 'is_active'], name='interview_r_rating_995ce6_idx')],
                'unique_together': {('session', 'reviewer', 'reviewer_type')},
            },
        ),
    ]
