# Generated by Django 4.2.7 on 2025-09-01 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('undergrad', 'Undergraduate'), ('ms', 'MS Student'), ('phd', 'PhD Student'), ('postdoc', 'Postdoc'), ('research_staff', 'Research Staff'), ('visiting', 'Visiting Researcher')], max_length=50)),
                ('duration', models.CharField(choices=[('< 1 year', 'Less than 1 year'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-4 years', '3-4 years'), ('4+ years', '4+ years')], max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('category_ratings', models.JSONField(default=dict)),
                ('review_text', models.TextField()),
                ('pros', models.JSONField(default=list)),
                ('cons', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='labs.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-helpful_count', '-created_at'],
                'unique_together': {('lab', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_helpful_votes',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
