# Generated by Django 4.2.7 on 2025-09-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='duration',
            field=models.CharField(choices=[('< 6 months', 'Less than 6 months'), ('6 months', '6 months'), ('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years'), ('4+ years', '4+ years')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.CharField(choices=[('PhD Student', 'PhD Student'), ('MS Student', 'MS Student'), ('Undergrad', 'Undergraduate Student'), ('PostDoc', 'PostDoc'), ('Research Assistant', 'Research Assistant')], max_length=50),
        ),
    ]
