# Generated by Django 4.2.7 on 2025-09-16 04:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_career_support_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rating Categories',
                'db_table': 'rating_categories',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='career_support_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='category_ratings',
        ),
        migrations.RemoveField(
            model_name='review',
            name='collaboration_culture_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='funding_resources_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='mentorship_quality_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='research_environment_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='work_life_balance_rating',
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.ratingcategory')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='reviews.review')),
            ],
            options={
                'db_table': 'review_ratings',
                'indexes': [models.Index(fields=['review', 'category'], name='review_rati_review__d1ef11_idx'), models.Index(fields=['category', 'rating'], name='review_rati_categor_e80319_idx')],
                'unique_together': {('review', 'category')},
            },
        ),
    ]
