# Generated by Django 4.2.7 on 2025-09-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_populate_rating_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('flagged', 'Flagged')], default='active', max_length=20),
        ),
    ]
