# Generated by Django 4.2.7 on 2025-10-25 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_remove_lab_professors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0006_professor_lab'),
        ('reviews', '0006_review_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='professor',
            field=models.ForeignKey(blank=True, help_text='Professor this review is about (required)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='universities.professor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='lab',
            field=models.ForeignKey(blank=True, help_text='Lab context for the review (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='labs.lab'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('professor', 'user')},
        ),
    ]
