# Generated by Django 4.2.7 on 2025-09-27 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_add_department_models'),
        ('authentication', '0003_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_department',
            field=models.ForeignKey(blank=True, help_text='University department where the user belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='universities.universitydepartment'),
        ),
    ]
