# Generated by Django 4.2.7 on 2025-09-29 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_alter_publication_table'),
        ('authentication', '0004_add_university_department_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLabInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_type', models.CharField(choices=[('general', 'General Interest'), ('application', 'Considering Application'), ('watching', 'Watching for Updates'), ('recruited', 'Applied/Recruited')], default='general', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about interest in this lab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='labs.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lab_interests',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'lab')},
            },
        ),
    ]
