# Generated by Django 4.2.7 on 2025-09-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_universityemaildomain'),
        ('authentication', '0005_userlabinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_email',
            field=models.EmailField(blank=True, help_text='University email for verification', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='university_email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='university_email_verification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='university_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_university',
            field=models.ForeignKey(blank=True, help_text='University verified through email domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to='universities.university'),
        ),
    ]
