# Generated by Django 4.2.7 on 2025-10-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_university_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ko', 'Korean'), ('en', 'English')], default='ko', help_text='User preferred language for emails and interface', max_length=10),
        ),
    ]
