# Generated by Django 4.2.7 on 2025-10-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_user_research_profile'),
        ('authentication', '0007_add_language_preference'),
    ]

    operations = [
    ]
