# Generated by Django 4.2.7 on 2025-12-28 09:11

from django.db import migrations
from django.db import connection


def remove_department_field_if_exists(apps, schema_editor):
    """Safely remove department field if it exists"""
    db_vendor = connection.vendor

    with connection.cursor() as cursor:
        # Check if the column exists before trying to remove it
        if db_vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name='users' AND column_name='department'
            """)
        elif db_vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(users)")
            columns = [row[1] for row in cursor.fetchall()]
            if 'department' in columns:
                cursor.execute('ALTER TABLE users DROP COLUMN department')
                return
            return
        else:
            # For other databases, try to get column info
            cursor.execute("DESCRIBE users")

        if db_vendor != 'sqlite' and cursor.fetchone():
            cursor.execute('ALTER TABLE users DROP COLUMN department')


def add_department_field_back(apps, schema_editor):
    """Add department field back (reverse operation)"""
    db_vendor = connection.vendor

    with connection.cursor() as cursor:
        # Check if the column doesn't exist before adding it back
        if db_vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name='users' AND column_name='department'
            """)
            if not cursor.fetchone():
                cursor.execute('ALTER TABLE users ADD COLUMN department varchar(255)')
        elif db_vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(users)")
            columns = [row[1] for row in cursor.fetchall()]
            if 'department' not in columns:
                cursor.execute('ALTER TABLE users ADD COLUMN department varchar(255)')
        else:
            # For other databases
            try:
                cursor.execute("DESCRIBE users")
                if not cursor.fetchone():
                    cursor.execute('ALTER TABLE users ADD COLUMN department varchar(255)')
            except:
                cursor.execute('ALTER TABLE users ADD COLUMN department varchar(255)')


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_merge_20251030_1034'),
    ]

    operations = [
        migrations.RunPython(
            remove_department_field_if_exists,
            add_department_field_back,
        ),
    ]
