# Generated by Django 4.2.7 on 2025-12-28 09:11

from django.db import migrations
from django.db import connection


def remove_department_field_if_exists(apps, schema_editor):
    """Safely remove department field if it exists"""
    with connection.cursor() as cursor:
        # Check if the column exists before trying to remove it
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='users' AND column_name='department'
        """)
        if cursor.fetchone():
            cursor.execute('ALTER TABLE users DROP COLUMN department')


def add_department_field_back(apps, schema_editor):
    """Add department field back (reverse operation)"""
    with connection.cursor() as cursor:
        # Check if the column doesn't exist before adding it back
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='users' AND column_name='department'
        """)
        if not cursor.fetchone():
            cursor.execute('ALTER TABLE users ADD COLUMN department varchar(255)')


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_merge_20251030_1034'),
    ]

    operations = [
        migrations.RunPython(
            remove_department_field_if_exists,
            add_department_field_back,
        ),
    ]
